export const discObj = [
  { nome: 'ALGORITMOS E ESTRUTURAS DE DADOS I', periodo: 1, pre: [], feito: false, id: 0 },
  { nome: 'CÁLCULO I', periodo: 1, pre: [], feito: false, id: 1 },
  { nome: 'DESENVOLVIMENTO DE INTERFACES WEB', periodo: 1, pre: [], feito: false, id: 2 },
  { nome: 'FUNDAMENTOS DE ENGENHARIA DE SOFTWARE', periodo: 1, pre: [], feito: false, id: 3 },
  { nome: 'INTRODUÇÃO À COMPUTAÇÃO', periodo: 1, pre: [], feito: false, id: 4 },
  { nome: 'TRABALHO INTERDISCIPLINAR: APLICAÇÕES WEB', periodo: 1, pre: [], feito: false, id: 5 },
  { nome: 'ALGORITMOS E ESTRUTURAS DE DADOS II', periodo: 2, pre: [0], feito: false, id: 6 },
  { nome: 'ARQUITETURA DE COMPUTADORES', periodo: 2, pre: [4], feito: false, id: 7 },
  { nome: 'BANCOS DE DADOS', periodo: 2, pre: [0], feito: false, id: 8 },
  { nome: 'CÁLCULO II', periodo: 2, pre: [1], feito: false, id: 9 },
  { nome: 'INTRODUÇÃO À PESQUISA EM INFORMÁTICA', periodo: 2, pre: [], feito: false, id: 10 },
  { nome: 'MODELAGEM DE PROCESSOS DE NEGÓCIOS', periodo: 2, pre: [3], feito: false, id: 11 },
  { nome: 'OPTATIVA', periodo: 2, pre: [], feito: false, id: 12 },
  { nome: 'TRABALHO INTERDISCIPLINAR: APLICAÇÕES PARA PROCESSOS DE NEGÓCIOS', periodo: 2, pre: [], feito: false, id: 13 },
  { nome: 'ENGENHARIA DE REQUISITOS DE SOFTWARE', periodo: 3, pre: [3], feito: false, id: 14 },
  { nome: 'LABORATÓRIO DE PROGRAMAÇÃO MODULAR', periodo: 3, pre: [], feito: false, id: 15 },
  { nome: 'PROGRAMAÇÃO MODULAR', periodo: 3, pre: [6], feito: false, id: 16 },
  { nome: 'SISTEMAS OPERACIONAIS', periodo: 3, pre: [7], feito: false, id: 17 },
  { nome: 'TEORIA DOS GRAFOS E COMPUTABILIDADE', periodo: 3, pre: [6], feito: false, id: 18 },
  { nome: 'TRABALHO INTERDISCIPLINAR: APLICAÇÕES PARA CENÁRIOS REAIS', periodo: 3, pre: [], feito: false, id: 19 },
  { nome: 'COMPUTADORES E SOCIEDADE', periodo: 4, pre: [], feito: false, id: 20 },
  { nome: 'FUNDAMENTOS DE PROJETO E ANÁLISE DE ALGORITMOS', periodo: 4, pre: [18], feito: false, id: 21 },
  { nome: 'INTERAÇÃO HUMANO-COMPUTADOR', periodo: 4, pre: [14], feito: false, id: 22 },
  { nome: 'LABORATÓRIO DE DESENVOLVIMENTO DE SOFTWARE', periodo: 4, pre: [], feito: false, id: 23 },
  { nome: 'OPTATIVA II', periodo: 4, pre: [], feito: false, id: 24 },
  { nome: 'PROJETO DE SOFTWARE', periodo: 4, pre: [14,16], feito: false, id: 25 },
  { nome: 'REDES DE COMPUTADORES', periodo: 4, pre: [17], feito: false, id: 26 },
  { nome: 'TRABALHO INTERDISCIPLINAR: APLICAÇÕES PARA SUSTENTABILIDADE', periodo: 4, pre: [], feito: false, id: 27 },
  { nome: 'ARQUITETURA DE SOFTWARE', periodo: 5, pre: [25], feito: false, id: 28 },
  { nome: 'DESENVOLVIMENTO DE APLICAÇÕES MÓVEIS E DISTRIBUÍDAS', periodo: 5, pre: [16,26], feito: false, id: 29 },
  { nome: 'ESTATÍSTICA E PROBABILIDADE', periodo: 5, pre: [1], feito: false, id: 30 },
  { nome: 'GERÊNCIA DE PROJETOS DE SOFTWARE', periodo: 5, pre: [14], feito: false, id: 31 },
  { nome: 'LABORATÓRIO DE DESENVOLVIMENTO DE APLICAÇÕES MÓVEIS E DISTRIBUÍDAS', periodo: 5, pre: [], feito: false, id: 32 },
  { nome: 'TESTE DE SOFTWARE', periodo: 5, pre: [14], feito: false, id: 33 },
  { nome: 'TRABALHO INTERDISCIPLINAR: APLICAÇÕES DISTRIBUÍDAS', periodo: 5, pre: [], feito: false, id: 34 },
  { nome: 'ENGENHARIA ECONÔMICA PARA SOFTWARE', periodo: 6, pre: [31], feito: false, id: 35 },
  { nome: 'FILOSOFIA: ANTROPOLOGIA E ÉTICA', periodo: 6, pre: [], feito: false, id: 36 },
  { nome: 'GERÊNCIA DE CONFIGURAÇÃO E EVOLUÇÃO DE SOFTWARE', periodo: 6, pre: [25], feito: false, id: 37 },
  { nome: 'LABORATÓRIO DE EXPERIMENTAÇÃO DE SOFTWARE', periodo: 6, pre: [], feito: false, id: 38 },
  { nome: 'MEDIÇÃO E EXPERIMENTAÇÃO EM ENGENHARIA DE SOFTWARE', periodo: 6, pre: [30], feito: false, id: 39 },
  { nome: 'OPTATIVA III', periodo: 6, pre: [], feito: false, id: 40 },
  { nome: 'TRABALHO INTERDISCIPLINAR: PESQUISA EM ENGENHARIA DE SOFTWARE', periodo: 6, pre: [], feito: false, id: 41 },
  { nome: 'CULTURA RELIGIOSA: FENÔMENO RELIGIOSO ', periodo: 7, pre: [], feito: false, id: 42 },
  { nome: 'ENGENHARIA DE PROCESSOS E QUALIDADE DE SOFTWARE', periodo: 7, pre: [14], feito: false, id: 43 },
  { nome: 'FILOSOFIA: RAZÃO E MODERNIDADE', periodo: 7, pre: [], feito: false, id: 44 },
  { nome: 'GESTÃO DA PRODUÇÃO DE SOFTWARE', periodo: 7, pre: [31], feito: false, id: 45 },
  { nome: 'TECNOLOGIAS DA INFORMAÇÃO E DO CONHECIMENTO', periodo: 7, pre: [11], feito: false, id: 46 },
  { nome: 'TÓPICOS EM COMPUTAÇÃO I', periodo: 7, pre: [21], feito: false, id: 47 },
  { nome: 'TÓPICOS EM COMPUTAÇÃO II', periodo: 7, pre: [21], feito: false, id: 48 },
  { nome: 'TÓPICOS EM ENGENHARIA DE SOFTWARE', periodo: 7, pre: [25], feito: false, id: 49 },
  { nome: 'TRABALHO DE CONCLUSÃO DE CURSO I', periodo: 7, pre: [10], feito: false, id: 50 },
  { nome: 'CULTURA RELIGIOSA: PESSOA E SOCIEDADE', periodo: 8, pre: [], feito: false, id: 51 },
  { nome: 'MODELAGEM E AVALIAÇÃO DE DESEMPENHO', periodo: 8, pre: [18,30], feito: false, id: 52 },
  { nome: 'OPTATIVA IV', periodo: 8, pre: [], feito: false, id: 53 },
  { nome: 'SEGURANÇA E AUDITORIA DE SISTEMAS', periodo: 8, pre: [25,26], feito: false, id: 54 },
  { nome: 'TÓPICOS EM SISTEMAS DE SOFTWARE', periodo: 8, pre: [], feito: false, id: 55 },
  { nome: 'TRABALHO DE CONCLUSÃO DE CURSO II', periodo: 8, pre: [50], feito: false, id: 56 },
]

